monitor = ,preferred,auto,1

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1
    layout = dwindle
}

animations {
    enabled = true
    bezier = smooth, 0.22, 1.0, 0.36, 1.0
    animation = windows, 1, 5, smooth, popin 90%
    animation = windowsMove, 1, 5, smooth
    animation = workspaces, 1, 7, smooth, slidefade 20%
    animation = fade, 1, 4, smooth
}

exec-once = foot

$mainMod = SUPER
bind = $mainMod, RETURN, exec, foot
bind = $mainMod SHIFT, RETURN, exec, ghostty
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, exit
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
