"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
palette = "nord"

format = '$username$hostname $directory$git_branch $character'

[username]
show_always = true
format = '[$user](bold nord8)'

[hostname]
ssh_only = true
ssh_symbol = ''
format = '[@$hostname](bold nord9)'
trim_at = '.'

[directory]
format = '[$path](bold nord4)'
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = ''
format = ' [\($branch\)](bold nord14)'

[character]
success_symbol = '[\$](bold nord8)'
error_symbol = '[\$](bold nord11)'
vimcmd_symbol = '[\$](bold nord14)'

[palettes.nord]
nord0  = "#2E3440"
nord1  = "#3B4252"
nord2  = "#434C5E"
nord3  = "#4C566A"
nord4  = "#D8DEE9"
nord5  = "#E5E9F0"
nord6  = "#ECEFF4"
nord7  = "#8FBCBB"
nord8  = "#88C0D0"
nord9  = "#81A1C1"
nord10 = "#5E81AC"
nord11 = "#BF616A"
nord12 = "#D08770"
nord13 = "#EBCB8B"
nord14 = "#A3BE8C"
nord15 = "#B48EAD"
